name: build only

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace searchPhoto.xcworkspace -scheme searchPhoto
    # - name: Run tests
    #   run: swift test -v
