name: swiftaction_test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ls
            pwd
            swift build -v
    - name: Run tests
      run: swift test -v
